fix: erc20 to erc20 ictt bridge chapter
ava-labs/avalanche-academy pull request #111
Opened 2024-09-05 16:54 UTC by owenwahlgren

This PR cleans up the erc-20 -> erc20 bridge using ICTT.
- Fix contract paths
- Rename / fix environment variables
- Add info about AvaCloud relayer
- Add submission process for listing on Core

2024-09-05 20:54 UTC, owenwahlgren commented
waiting on gform from avacloud 👍

2024-09-05 21:56 UTC, martineckardt commented
We have duplicate instructions to create a blockchain. The first time in the [Environment Setup](https://avalanche-academy-git-ictt-sendandcall-ava-labs.vercel.app/course/interchain-token-transfer/02-avalanche-starter-kit/03-create-blockchain) chapter using the [content/commmon/avalanche-starter-kit/create-default-blockchain instructions](https://github.com/ava-labs/avalanche-academy/blob/erc20-erc20-ictt-fix/content/common/avalanche-starter-kit/create-default-blockchain.mdx) and then later in the [ERC-20-to-ERC-20 Bridge](https://avalanche-academy-git-ictt-sendandcall-ava-labs.vercel.app/course/interchain-token-transfer/06-erc-20-to-erc-20-bridge/01-erc-20-to-erc-20-bridge) chapter using the [content/commmon/avalanche-ictt/setup-manual.mdx](https://github.com/ava-labs/avalanche-academy/pull/111/files#diff-67d81a597cae8f61b08962c0973bff9c42620d40959fa4b443085189c44c5f48) instructions.

- [ ] Can we delete the `content/commmon/avalanche-ictt/setup-manual.mdx`? I don't see a difference, the output is outdated and want to reduce as much as possible
- [ ] The blockchain created in the `Environment Setup` chapter never gets used as far as I can tell. Should we just move the chapter after the `Tokens`, `Token Bridging` and `Interchain Token Transfer` chapter? Then we can use the blockchain created in the `Environment Setup` for the bridge
- [ ] Add the environment variables that are constant to the `devcontainer.json` of the starter kit

2024-09-05 21:57 UTC, martineckardt requested changes

2024-09-05 21:57 UTC, martineckardt commented on content/common/avalanche-ictt/setup-manual.mdx
>  export FUNDED_ADDRESS=<Funded Address (with 100 tokens)>
Let's add this to the `devcontainer.json` of the Starter Kit and set it to the EWOQ Address

2024-09-05 21:57 UTC, martineckardt commented on content/common/avalanche-ictt/setup-manual.mdx
>  export TELEPORTER_REGISTRY_C_CHAIN=<Interchain Messaging Registry on C-chain>
This one should be constant too, so we can add that as well to the devcontainer.json

2024-09-05 21:57 UTC, martineckardt commented on content/common/avalanche-ictt/setup-manual.mdx
> +export TELEPORTER_REGISTRY_L1=<Interchain Messaging Registry on Avalanche L1>
Not sure about this one, please try if it's always the same. If it is, lets also add to `devcontainer.json`

2024-09-06 20:31 UTC, owenwahlgren commented
should be merged alongside https://github.com/ava-labs/avalanche-starter-kit/pull/33

2024-09-06 20:41 UTC, martineckardt approved these changes

2024-09-06 20:41 UTC, merged